### ISSUE TITLE
Postfix and Solve with token support

### ISSUE THREAD

**Issue by tylorhl** [zachChilders/SpreadSheet#3]
> using #1 `Tokenizer` and `tokens` under `Solve()`

Modify the solving and the postfix portions of the code to support the new token type.

**Comment by zachChilders** [comment]
I updated everything to string, we should be good to go.  
There are currently two errors in Formula, because postfix() used to take a string as input. It now takes string [], which is some form of the output of Tokenizer.  When the methods are available, the string being passed to postfix() simply will need to be Tokenized.  Closed for now.

**Comment by tylorhl** [comment]
I modified Formula slightly in response to the additions I made today. I didn't touch your algorithms, though.

Tokenization should be set up pretty nicely now. The only thing it needs is the actual Tokenizing implementation, which should be handled in #2.

Luckily with your algorithm currently in place, there should only need to be minimal changes to support the Tokenizing.

For instance:

``` C#
private static String postFix(Queue<FormulaToken> infix)
{
    ....
    for (int i = 0; i < infix.Length; i++)
    ....
}
```

can really just be replaced with popping the Queue that comes with Tokenizing.

Even the banana check can be pretty close to what it is now:

``` C#
StringBuilder tmp = new StringBuilder();
for (int t = i; infix[t] != ")"; t++, i++)
{
    tmp.Append(infix[t]);
}
```

Can become something like:

``` C#
Queue<FormulaToken>tmp = new Queue<FormulaToken>();
FormulaToken t;
while((t = tmp.Dequeue()).Token != ")")
{
    tmp.Enqueue(t);
}
```

**Comment by zachChilders** [comment]
Implemented as described.
